### ISSUE TITLE
AttributeError: module 'typing' has no attribute '_ClassVar'

### ISSUE THREAD

**Issue by pkorzh** [power-of-language/oneai_sdk_python#1]
Execution env: AWS Lambda python 3.9

Code:

```
    pipeline = oneai.Pipeline(
        steps = [
            oneai.skills.Summarize()
        ]
    )

    conversation = oneai.Conversation([oneai.Utterance(sender, body) for sender, body in conversation])

    output = pipeline.run(conversation)
    return output.summary.text
```

Error:

```
[ERROR] AttributeError: module 'typing' has no attribute '_ClassVar'
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 8, in <module>
    import oneai
  File "/var/task/oneai/__init__.py", line 5, in <module>
    import oneai.skills as skills
  File "/var/task/oneai/skills.py", line 5, in <module>
    from oneai.classes import Skill, skillclass
  File "/var/task/oneai/classes.py", line 14, in <module>
    class Skill:
  File "/var/task/dataclasses.py", line 958, in dataclass
    return wrap(_cls)
  File "/var/task/dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/var/task/dataclasses.py", line 800, in _process_class
    cls_fields = [_get_field(cls, name, type)
  File "/var/task/dataclasses.py", line 800, in <listcomp>
    cls_fields = [_get_field(cls, name, type)
  File "/var/task/dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
  File "/var/task/dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
```

**Comment by michgur** [comment]
Can you try running
`pip uninstall dataclasses -y`

I'll update the setup configuration to not install this for python version>3.7
